[tool.poetry]
name = "pre-commit-hooks"
version = "0.7.0"
description = ""
authors = ["Your Name <you@example.com>"]
include = [
  "pre_commit_hooks/*",
  "submodule_pre_commit_hooks/pre_commit_hooks/*"
]

[tool.poetry.scripts]
end-of-file-fixer="submodule_pre_commit_hooks.pre_commit_hooks.end_of_file_fixer:main"
trailing-whitespace-fixer="submodule_pre_commit_hooks.pre_commit_hooks.trailing_whitespace_fixer:main"
pretty-format-json="submodule_pre_commit_hooks.pre_commit_hooks.pretty_format_json:main"
requirements-txt-fixer="submodule_pre_commit_hooks.pre_commit_hooks.requirements_txt_fixer:main"

[tool.poetry.dependencies]
python = "^3.7"
yamllint = "^v1.25.0"
detect-secrets = { git = "https://github.com/ibm/detect-secrets.git", tag = "0.13.1+ibm.46.dss" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
